name       : pyenchant
version    : 1.6.8
release    : 1
source     :
    - https://pypi.python.org/packages/73/73/49f95fe636ab3deed0ef1e3b9087902413bcdf74ec00298c3059e660cfbb/pyenchant-1.6.8.tar.gz : 7ead2ee74f1a4fc2a7199b3d6012eaaaceea03fbcadcb5df67d2f9d0d51f050a
license    : LGPL-2.1
component  : programming.python
summary    : Python language bindings for enchant.
description: |
    Python language bindings for enchant.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(python-3.5)
rundeps    :
    - enchant
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
