name       : pyenchant
version    : 2.0.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/p/pyenchant/pyenchant-2.0.0.tar.gz : fc31cda72ace001da8fe5d42f11c26e514a91fa8c70468739216ddd8de64e2a0
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python language bindings for enchant
description: |
    Python bindings for the Enchant spellchecker
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(python3)
    - hunspell-en       #check
rundeps    :
    - enchant16
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
