name       : pyenchant
version    : 2.0.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pyenchant/pyenchant-2.0.0.tar.gz : fc31cda72ace001da8fe5d42f11c26e514a91fa8c70468739216ddd8de64e2a0
license    : LGPL-2.1
component  : programming.python
summary    : Python language bindings for enchant
description: |
    Python bindings for the Enchant spellchecker
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(python-3.5)
    - hunspell-en       #check
    - python-setuptools
rundeps    :
    - enchant
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    export LC_ALL=en_US.utf8

    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
