name       : pyenchant
version    : 1.6.11
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/p/pyenchant/pyenchant-1.6.11.tar.gz : 27d3307aa3d3cd413c20eb1fd977446c133cae47d7329d8f846cd3d8ddae6278
license    : LGPL-2.1
component  : programming.python
summary    : Python language bindings for enchant
description: |
    Python bindings for the Enchant spellchecker
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - enchant
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
